-- 1. Top 10 customers by lifetime value (from orders)
SELECT CustomerID,
       COUNT(DISTINCT Invoice) AS order_count,
       SUM(TotalPrice) AS lifetime_value,
       AVG(TotalPrice) AS avg_order
FROM orders
GROUP BY CustomerID
ORDER BY lifetime_value DESC
LIMIT 10;

-- 2. Monthly revenue growth rate (using LAG)
WITH monthly_revenue AS (
    SELECT SUBSTR(InvoiceDate, 1, 7) AS month,
           SUM(TotalPrice) AS revenue
    FROM orders
    GROUP BY month
)
SELECT month,
       revenue,
       LAG(revenue) OVER (ORDER BY month) AS prev_month,
       ROUND((revenue - LAG(revenue) OVER (ORDER BY month)) / LAG(revenue) OVER (ORDER BY month) * 100, 2) AS growth_pct
FROM monthly_revenue
ORDER BY month;

-- 3. Customer retention: Customers who bought in 2009 AND 2010
SELECT COUNT(DISTINCT CustomerID) AS retained_customers
FROM orders
WHERE CustomerID IN (
    SELECT CustomerID FROM orders WHERE InvoiceDate LIKE '2009%'
)
AND CustomerID IN (
    SELECT CustomerID FROM orders WHERE InvoiceDate LIKE '2010%'
);

-- 4. New customers by year (first purchase year)
SELECT SUBSTR(InvoiceDate, 1, 4) AS first_year,
       COUNT(DISTINCT CustomerID) AS new_customers
FROM (
    SELECT CustomerID, MIN(InvoiceDate) AS first_purchase
    FROM orders
    GROUP BY CustomerID
)
WHERE first_purchase IS NOT NULL
GROUP BY first_year
ORDER BY first_year;

-- 5. Average order value by country (including only countries with > 100 orders)
SELECT Country,
       ROUND(AVG(TotalPrice), 2) AS avg_order_value,
       COUNT(*) AS order_count
FROM orders
GROUP BY Country
HAVING COUNT(*) > 100
ORDER BY avg_order_value DESC;

-- 6. Pareto Analysis: Top 20% of customers drive what % of revenue?
WITH customer_spend AS (
    SELECT CustomerID, SUM(TotalPrice) AS total_spent
    FROM orders
    GROUP BY CustomerID
),
ranked AS (
    SELECT CustomerID,
           total_spent,
           ROW_NUMBER() OVER (ORDER BY total_spent DESC) AS rank_order,
           COUNT(*) OVER () AS total_customers
    FROM customer_spend
)
SELECT SUM(total_spent) * 100.0 / (SELECT SUM(total_spent) FROM customer_spend) AS pct_revenue
FROM ranked
WHERE rank_order <= ROUND(total_customers * 0.2, 0);

-- 7. Churn risk: Customers who haven't purchased in the last 3 months (from snapshot date 2011-12-10)
SELECT CustomerID,
       MAX(InvoiceDate) AS last_purchase,
       JULIANDAY('2011-12-10') - JULIANDAY(MAX(InvoiceDate)) AS days_since_purchase
FROM orders
GROUP BY CustomerID
HAVING days_since_purchase > 90
ORDER BY days_since_purchase DESC;

-- 8. Product analysis: Top 5 products by revenue
SELECT StockCode,
       Description,
       SUM(TotalPrice) AS total_revenue,
       COUNT(DISTINCT Invoice) AS times_ordered
FROM orders
GROUP BY StockCode, Description
ORDER BY total_revenue DESC
LIMIT 5;

-- 9. Average order size (items) by country
SELECT Country,
       ROUND(AVG(Quantity), 2) AS avg_items_per_order
FROM orders
GROUP BY Country
HAVING COUNT(*) > 10
ORDER BY avg_items_per_order DESC
LIMIT 10;

-- 10. High-value customers: Those with orders > $1000
SELECT CustomerID,
       COUNT(DISTINCT Invoice) AS high_value_orders,
       SUM(TotalPrice) AS total_high_value_spend
FROM orders
WHERE TotalPrice > 1000
GROUP BY CustomerID
ORDER BY total_high_value_spend DESC
LIMIT 10;

-- 11. Monthly cohort analysis: Retention by month
SELECT SUBSTR(InvoiceDate, 1, 7) AS cohort_month,
       COUNT(DISTINCT CustomerID) AS customer_count
FROM orders
GROUP BY cohort_month
ORDER BY cohort_month;

-- 12. Product category distribution (using Description prefixes)
SELECT SUBSTR(Description, 1, 3) AS category,
       COUNT(*) AS frequency,
       SUM(TotalPrice) AS revenue
FROM orders
WHERE Description IS NOT NULL
GROUP BY category
ORDER BY revenue DESC
LIMIT 10;

-- 13. Seasonal analysis: Best and worst months for revenue
SELECT SUBSTR(InvoiceDate, 6, 2) AS month,
       ROUND(SUM(TotalPrice), 2) AS total_revenue,
       ROUND(AVG(TotalPrice), 2) AS avg_order_value
FROM orders
GROUP BY month
ORDER BY month;

-- 14. Repeat purchase rate: How many customers are repeat buyers?
WITH customer_orders AS (
    SELECT CustomerID,
           COUNT(DISTINCT Invoice) AS order_count
    FROM orders
    GROUP BY CustomerID
)
SELECT 
    CASE 
        WHEN order_count = 1 THEN 'One-time'
        WHEN order_count <= 5 THEN '2-5 orders'
        ELSE '6+ orders'
    END AS purchase_category,
    COUNT(*) AS customer_count,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM customer_orders), 2) AS pct_of_customers
FROM customer_orders
GROUP BY purchase_category;

-- 15. Customer acquisition cost proxy: Revenue generated by customers acquired in each month
WITH first_purchase AS (
    SELECT CustomerID,
           SUBSTR(MIN(InvoiceDate), 1, 7) AS acquisition_month,
           MIN(InvoiceDate) AS first_date
    FROM orders
    GROUP BY CustomerID
)
SELECT fp.acquisition_month,
       COUNT(DISTINCT fp.CustomerID) AS new_customers,
       ROUND(SUM(o.TotalPrice), 2) AS total_revenue_from_cohort
FROM first_purchase fp
INNER JOIN orders o ON fp.CustomerID = o.CustomerID
GROUP BY fp.acquisition_month
ORDER BY fp.acquisition_month;
